on:
  push:
    branches: [master]

name: Deploy Staging

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.STAGING_SERVERLESS_ACCESS_KEY }}

jobs:
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Serverless
        run: |
          export SERVERLESS_ACCESS_KEY="$SERVERLESS_ACCESS_KEY"

      - name: Deploy API
        run: |
          cd StreamingLiveApi
          npm install
          npm run deploy-staging

      - name: Deploy Chat
        run: |
          cd StreamingLiveChat
          npm install
          npm run deploy-staging

      - name: Deploy Admin
        run: |
          cd StreamingLiveAdmin
          npm install
          npm run deploy-staging
      
      - name: Deploy Sub
        run: |
          cd StreamingLiveSub
          npm install
          npm run deploy-staging

      - name: Deploy Web
        run: |
          cd StreamingLiveWeb
          npm install
          npm run deploy-staging
